INSERT INTO UF VALUES (1, 33, 'Rio de Janeiro', FILE_READ('D:\sntsb\Documents\datasus-bd\bandeiras\Bandeira_do_estado_do_Rio_de_Janeiro.svg'), NULL);
INSERT INTO UF VALUES (2, 12, 'Acre', FILE_READ('D:\sntsb\Documents\datasus-bd\bandeiras/Bandeira_do_Acre.svg'),NULL);
INSERT INTO UF VALUES (3, 27, 'Alagoas', FILE_READ('D:\sntsb\Documents\datasus-bd\bandeiras/Bandeira_de_Alagoas.svg.png'), NULL);
INSERT INTO UF VALUES (4, 25, 'Paraíba', FILE_READ('D:\sntsb\Documents\datasus-bd\bandeiras/Bandeira_da_Paraíba.svg'), NULL);
INSERT INTO UF VALUES (5, 35, 'São Paulo', FILE_READ('D:\sntsb\Documents\datasus-bd\bandeiras/Bandeira_do_estado_de_São_Paulo.svg.png'), NULL);
INSERT INTO UF VALUES (6, 13, 'Amazonas', FILE_READ('D:\sntsb\Documents\datasus-bd\bandeiras/Bandeira_do_Amazonas.svg.png'), NULL);
INSERT INTO UF VALUES (7, 23, 'Ceará', FILE_READ('D:\sntsb\Documents\datasus-bd\bandeiras/Bandeira_do_Ceará.svg.png'), NULL);
INSERT INTO UF VALUES (8, 31, 'Minas Gerais', FILE_READ('D:\sntsb\Documents\datasus-bd\bandeiras/Bandeira_de_Minas_Gerais.svg.png'), NULL);
INSERT INTO UF VALUES (9, 29, 'Bahia', FILE_READ('D:\sntsb\Documents\datasus-bd\bandeiras/Bandeira_da_Bahia.svg'), NULL);
INSERT INTO UF VALUES (10, 32, 'Espírito Santo', FILE_READ('D:\sntsb\Documents\datasus-bd\bandeiras/Bandeira_do_Espírito_Santo.svg.png'), NULL);

INSERT INTO Vacina VALUES (1, NULL, 'SINOVAC');
INSERT INTO Vacina VALUES (2, 'BUTANTAN', 'SINOVAC');
INSERT INTO Vacina VALUES (3, NULL, 'PFIZER');
INSERT INTO Vacina VALUES (4, NULL, 'ASTRAZENECA');
INSERT INTO Vacina VALUES (5, 'FIOCRUZ', 'ASTRAZENECA');
INSERT INTO Vacina VALUES (6, NULL, 'JANSSEN');

INSERT INTO Municipio VALUES (1, 'Rio de Janeiro', 1);
INSERT INTO Municipio VALUES (2, 'Niterói', 1);
INSERT INTO Municipio VALUES (3, 'Cruzeiro do Sul', 2);
INSERT INTO Municipio VALUES (4, 'Rio Branco', 2);
INSERT INTO Municipio VALUES (5, 'Viçosa', 3);
INSERT INTO Municipio VALUES (6, 'Maceió', 3);
INSERT INTO Municipio VALUES (7, 'Serra Redonda', 4);
INSERT INTO Municipio VALUES (8, 'Itaporanga', 4);
INSERT INTO Municipio VALUES (9, 'Guarulhos', 5);
INSERT INTO Municipio VALUES (10, 'Osasco', 5);
INSERT INTO Municipio VALUES (11, 'Manaus', 6);
INSERT INTO Municipio VALUES (12, 'Alvarães', 6);
INSERT INTO Municipio VALUES (13, 'Fortaleza', 7);
INSERT INTO Municipio VALUES (14, 'Camocim', 7);
INSERT INTO Municipio VALUES (15, 'Belo Horizonte', 8);
INSERT INTO Municipio VALUES (16, 'Três Marias', 8);
INSERT INTO Municipio VALUES (17, 'Salvador', 9);
INSERT INTO Municipio VALUES (18, 'Alagoinhas', 9);
INSERT INTO Municipio VALUES (19, 'Vitória', 10);
INSERT INTO Municipio VALUES (20, 'Santa Teresa', 10);

INSERT INTO Sintomas VALUES (1, 'Assintomático');
INSERT INTO Sintomas VALUES (2, 'Febre');
INSERT INTO Sintomas VALUES (3, 'Outros');
INSERT INTO Sintomas VALUES (4, 'Tosse');
INSERT INTO Sintomas VALUES (5, 'Dispneia');
INSERT INTO Sintomas VALUES (6, 'Dor de Garganta');
INSERT INTO Sintomas VALUES (7, 'Distúrbios Gustativos');
INSERT INTO Sintomas VALUES (8, 'Distúrbios Olfativos');
INSERT INTO Sintomas VALUES (9, 'Coriza');
INSERT INTO Sintomas VALUES (10, 'Dor de Cabeça');

INSERT INTO REL_TESTE__SINTOMAS VALUES (1,1);
INSERT INTO REL_TESTE__SINTOMAS VALUES (1,2);
INSERT INTO REL_TESTE__SINTOMAS VALUES (1,3);
INSERT INTO REL_TESTE__SINTOMAS VALUES (1,4);
INSERT INTO REL_TESTE__SINTOMAS VALUES (1,5);
INSERT INTO REL_TESTE__SINTOMAS VALUES (1,6);
INSERT INTO REL_TESTE__SINTOMAS VALUES (1,7);
INSERT INTO REL_TESTE__SINTOMAS VALUES (1,8);
INSERT INTO REL_TESTE__SINTOMAS VALUES (1,9);
INSERT INTO REL_TESTE__SINTOMAS VALUES (1,10);
